FROM eclipse-temurin:17-jre-alpine

ARG DIR_PATH=/seung
ARG LOG_PATH=${DIR_PATH}/log
ARG JAR_PATH=${DIR_PATH}/app.jar

RUN apk update && apk upgrade

RUN mkdir -p ${LOG_PATH}

RUN addgroup -S seung && adduser -S seung -G seung
RUN chown -R seung:root ${DIR_PATH}
USER seung

COPY build/libs/*.jar ${JAR_PATH}

ENV RUN_COMMAND="java -jar ${JAR_PATH}"

CMD $RUN_COMMAND
